Initial docker commit
SuperSolik/gui_1h2020-notes-app pull request #16
Opened 2020-05-10 19:07 UTC by VeselAbaya

2020-05-10 19:21 UTC, SuperSolik commented on Dockerfile
> +FROM ubuntu:18.04
почему не `FROM python:3.8`, как например [здесь](https://github.com/alexey-goloburdin/telegram-finance-bot/blob/master/Dockerfile)? Не надо pip ставить отдельно. Есть ли разница с тем чтобы ставить целый образ убунты?

2020-05-10 19:22 UTC, SuperSolik requested changes
Не установлена переменная DEV_TEST_DB для бд, используется в db.py

2020-05-10 19:36 UTC, VeselAbaya commented on Dockerfile
> +FROM ubuntu:18.04
Не получится тогда с гуи запустить

2020-05-10 19:41 UTC, VeselAbaya commented on Dockerfile
> +FROM ubuntu:18.04
Не понел. При запуске контейнера устанаваливается переменная DEV_NOTE_DB

2020-05-10 19:47 UTC, SuperSolik commented on Dockerfile
> +FROM ubuntu:18.04
А, увидел, просто есть команда ENV докеровская, почему ее не юзанул, раз уж на то пошло

2020-05-10 19:50 UTC, VeselAbaya commented on Dockerfile
> +FROM ubuntu:18.04
Потому что я дебил

2020-05-13 19:23 UTC, SuperSolik approved these changes

2020-05-13 19:24 UTC, merged